command: ["sh", "start.sh"]
env:
  - name: DATABRICKS_WAREHOUSE_ID
    value: ea576f572ba19fea
  - name: BACKEND_API_URL
    value: "http://localhost:9000"
  - name: NEO4J_URI
    valueFrom: secret-4
  - name: NEO4J_USER
    valueFrom: secret-6
  - name: NEO4J_PASSWORD
    valueFrom: secret-3
  - name: NEO4J_DATABASE
    valueFrom: secret-5
  - name: GENIE_SPACE_ID
    value: "01f148e5845f1f68843892ceb53abd32"
  - name: PYTHONUNBUFFERED
    value: "1"
